/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import dao.ClienteDAO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;

/**
 *
 * @author aluno
 */
public class ConsumoForm extends javax.swing.JFrame {

    PrincipalForm princ;
    private ClienteDAO clientedao = new ClienteDAO();
    private List<Cliente> clientes;
    int i = 0;
    private Cliente clienteselecionado;

    /**
     * Creates new form consumo_energia
     */
    public ConsumoForm(PrincipalForm prin) {
        princ = prin;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtfValorTotal = new javax.swing.JTextField();
        jtfNome = new javax.swing.JTextField();
        jtfEndereco = new javax.swing.JTextField();
        jtfCep = new javax.swing.JTextField();
        jtfBairro = new javax.swing.JTextField();
        jtfCpf = new javax.swing.JTextField();
        jtfNascimento = new javax.swing.JTextField();
        jtfVencimento = new javax.swing.JTextField();
        jtfUnidadeConsumidora = new javax.swing.JTextField();
        jtfEmail = new javax.swing.JTextField();
        jtfKwh = new javax.swing.JTextField();
        jCBSexo = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jtfSite = new javax.swing.JTextField();
        jBExcluir = new javax.swing.JButton();
        jBXCancelar = new javax.swing.JButton();
        jBAlterar = new javax.swing.JButton();
        jBSalvar = new javax.swing.JButton();
        jBCadastrar = new javax.swing.JButton();
        jCBTermo = new javax.swing.JComboBox<>();
        jTFPesquisa = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTListaClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Valor total:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Nome:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Sexo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Endereço:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("CEP:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("Bairro:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("CPF:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("Nascimento:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setText("Data Vencimento:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setText("Unidade Consumidora:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setText("Email:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setText("Kwh:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        jtfValorTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfValorTotalActionPerformed(evt);
            }
        });
        jPanel1.add(jtfValorTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 230, 30));

        jtfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomeActionPerformed(evt);
            }
        });
        jPanel1.add(jtfNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 270, 30));

        jtfEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEnderecoActionPerformed(evt);
            }
        });
        jPanel1.add(jtfEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 240, 30));

        jtfCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCepActionPerformed(evt);
            }
        });
        jPanel1.add(jtfCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 300, 30));

        jtfBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBairroActionPerformed(evt);
            }
        });
        jPanel1.add(jtfBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 270, 30));

        jtfCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCpfActionPerformed(evt);
            }
        });
        jPanel1.add(jtfCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 290, 30));

        jtfNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNascimentoActionPerformed(evt);
            }
        });
        jPanel1.add(jtfNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 210, 30));

        jtfVencimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfVencimentoActionPerformed(evt);
            }
        });
        jPanel1.add(jtfVencimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 150, 30));

        jtfUnidadeConsumidora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfUnidadeConsumidoraActionPerformed(evt);
            }
        });
        jPanel1.add(jtfUnidadeConsumidora, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 100, 30));

        jtfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEmailActionPerformed(evt);
            }
        });
        jPanel1.add(jtfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 280, 30));

        jtfKwh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfKwhActionPerformed(evt);
            }
        });
        jPanel1.add(jtfKwh, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 290, 30));

        jCBSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MASCULINO", "FEMININO" }));
        jCBSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBSexoActionPerformed(evt);
            }
        });
        jPanel1.add(jCBSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 280, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel14.setText("Site:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));

        jtfSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSiteActionPerformed(evt);
            }
        });
        jPanel1.add(jtfSite, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 300, 30));

        jBExcluir.setBackground(new java.awt.Color(255, 0, 0));
        jBExcluir.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jBExcluir.setForeground(new java.awt.Color(255, 255, 255));
        jBExcluir.setText("Excluir");
        jBExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(jBExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 580, 90, 45));

        jBXCancelar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jBXCancelar.setText("Cancelar");
        jBXCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBXCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBXCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jBXCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 580, 100, 45));

        jBAlterar.setBackground(new java.awt.Color(0, 0, 0));
        jBAlterar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jBAlterar.setForeground(new java.awt.Color(255, 255, 255));
        jBAlterar.setText("Alterar");
        jBAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarActionPerformed(evt);
            }
        });
        jPanel1.add(jBAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 580, 90, 45));

        jBSalvar.setBackground(new java.awt.Color(0, 204, 255));
        jBSalvar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jBSalvar.setForeground(new java.awt.Color(255, 255, 255));
        jBSalvar.setText("Salvar");
        jBSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(jBSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 580, 80, 45));

        jBCadastrar.setBackground(new java.awt.Color(0, 153, 0));
        jBCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jBCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        jBCadastrar.setText("Cadastrar");
        jBCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jBCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 580, -1, 45));

        jCBTermo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCBTermo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "CPF", "Endereco" }));
        jPanel1.add(jCBTermo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 144, 40));

        jTFPesquisa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(jTFPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 340, 40));

        jButton11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton11.setText("Pesquisar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 30, 100, 40));

        jTListaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "CPF", "Endereco"
            }
        ));
        jScrollPane1.setViewportView(jTListaClientes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 620, 470));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfValorTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfValorTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfValorTotalActionPerformed

    private void jtfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomeActionPerformed

    private void jtfEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEnderecoActionPerformed

    private void jtfCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCepActionPerformed

    private void jtfBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfBairroActionPerformed

    private void jtfCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCpfActionPerformed

    private void jtfNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNascimentoActionPerformed

    private void jtfVencimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfVencimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfVencimentoActionPerformed

    private void jtfUnidadeConsumidoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfUnidadeConsumidoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfUnidadeConsumidoraActionPerformed

    private void jtfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEmailActionPerformed

    private void jtfKwhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfKwhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfKwhActionPerformed

    private void jCBSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBSexoActionPerformed

    private void jtfSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSiteActionPerformed

    private void jBXCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBXCancelarActionPerformed
        // TODO add your handling code here:

        princ.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBXCancelarActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        atualizarTabela();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        int linha = jTListaClientes.getSelectedRow();
        if (linha < 0) {
            JOptionPane.showMessageDialog(null, "Selecione uma pessoa", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        clienteselecionado = clientes.get(linha);
        try {
            clientedao.remover(clienteselecionado.getId());
            JOptionPane.showMessageDialog(null, "Pessoa excluída");
            atualizarTabela();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jBAlterarActionPerformed

    private void jBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarActionPerformed
        // TODO add your handling code here:
        String nome = jtfNome.getText();
        String sexo = jCBSexo.getSelectedItem().toString();
        String endereco = jtfEndereco.getText();
        String cep = jtfEndereco.getText();
        String bairro = jtfEndereco.getText();
        String cpf = jtfEndereco.getText();
        String nascimento = jtfEndereco.getText();
        String vencimento = jtfEndereco.getText();
        String unidade = jtfEndereco.getText();
        String email = jtfEndereco.getText();
        String kwh = jtfEndereco.getText();
        String valorTotal = jtfEndereco.getText();
        String site = jtfEndereco.getText();
        
    }//GEN-LAST:event_jBSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    private void atualizarTabela() {
        DefaultTableModel model = (DefaultTableModel) jTListaClientes.getModel();
        model.setNumRows(0);

        try {
            clientes = clientedao.pesquisarClientes(jCBTermo.getSelectedItem().toString().toLowerCase(), jTFPesquisa.getText());
            for (int i = 0; i < clientes.size(); i++) {
                Cliente cli = clientes.get(i);
                model.addRow(new Object[]{cli.getNome(), cli.getCpf(), cli.getEndereco(),cli.getBairro()});
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAlterar;
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBSalvar;
    private javax.swing.JButton jBXCancelar;
    private javax.swing.JButton jButton11;
    private javax.swing.JComboBox<String> jCBSexo;
    private javax.swing.JComboBox<String> jCBTermo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFPesquisa;
    private javax.swing.JTable jTListaClientes;
    private javax.swing.JTextField jtfBairro;
    private javax.swing.JTextField jtfCep;
    private javax.swing.JTextField jtfCpf;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfEndereco;
    private javax.swing.JTextField jtfKwh;
    private javax.swing.JTextField jtfNascimento;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfSite;
    private javax.swing.JTextField jtfUnidadeConsumidora;
    private javax.swing.JTextField jtfValorTotal;
    private javax.swing.JTextField jtfVencimento;
    // End of variables declaration//GEN-END:variables
}
