/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import dao.ClienteDAO;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import modelo.Cliente;
import modelo.Pessoa;

/**
 *
 * @author aluno
 */
public class ConsumoForm extends javax.swing.JFrame {

    private ClienteDAO clientedao = new ClienteDAO();
    int i = 0;

    /**
     * Creates new form consumo_energia
     */
    public ConsumoForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtfValorTotal = new javax.swing.JTextField();
        jtfNome = new javax.swing.JTextField();
        jtfEndereco = new javax.swing.JTextField();
        jtfCep = new javax.swing.JTextField();
        jtfBairro = new javax.swing.JTextField();
        jtfCpf = new javax.swing.JTextField();
        jtfNascimento = new javax.swing.JTextField();
        jtfVencimento = new javax.swing.JTextField();
        jtfUnidadeConsumidora = new javax.swing.JTextField();
        jtfEmail = new javax.swing.JTextField();
        jtfKwh = new javax.swing.JTextField();
        cbSexo = new javax.swing.JComboBox<>();
        btnCadastrar = new javax.swing.JButton();
        btnGerarNota2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jtfSite = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("CADASTRO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 6, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Valor total:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 506, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 66, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Sexo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 106, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Endereço:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 146, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("CEP:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 186, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("Bairro:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 226, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("CPF:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 266, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("Nascimento:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 306, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setText("Data Vencimento:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 346, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setText("Unidade Consumidora:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 386, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setText("Email:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 426, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setText("Kwh:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 466, -1, -1));

        jtfValorTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfValorTotalActionPerformed(evt);
            }
        });
        getContentPane().add(jtfValorTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 506, 320, 30));

        jtfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jtfNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 66, 320, 30));

        jtfEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(jtfEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 146, 320, 30));

        jtfCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCepActionPerformed(evt);
            }
        });
        getContentPane().add(jtfCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 186, 320, 30));

        jtfBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBairroActionPerformed(evt);
            }
        });
        getContentPane().add(jtfBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 226, 320, 30));

        jtfCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCpfActionPerformed(evt);
            }
        });
        getContentPane().add(jtfCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 266, 320, 30));

        jtfNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNascimentoActionPerformed(evt);
            }
        });
        getContentPane().add(jtfNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 306, 320, 30));

        jtfVencimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfVencimentoActionPerformed(evt);
            }
        });
        getContentPane().add(jtfVencimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 346, 320, 30));

        jtfUnidadeConsumidora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfUnidadeConsumidoraActionPerformed(evt);
            }
        });
        getContentPane().add(jtfUnidadeConsumidora, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 386, 320, 30));

        jtfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEmailActionPerformed(evt);
            }
        });
        getContentPane().add(jtfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 426, 320, 30));

        jtfKwh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfKwhActionPerformed(evt);
            }
        });
        getContentPane().add(jtfKwh, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 466, 320, 30));

        cbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PREFIRO NÃO DIZER", "MASCULINO", "FEMININO" }));
        cbSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSexoActionPerformed(evt);
            }
        });
        getContentPane().add(cbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 106, 260, 30));

        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 590, 190, -1));

        btnGerarNota2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnGerarNota2.setText("Gerar Nota");
        btnGerarNota2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarNota2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnGerarNota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, 190, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel14.setText("Site:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));

        jtfSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSiteActionPerformed(evt);
            }
        });
        getContentPane().add(jtfSite, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, 320, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfValorTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfValorTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfValorTotalActionPerformed

    private void jtfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomeActionPerformed

    private void jtfEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEnderecoActionPerformed

    private void jtfCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCepActionPerformed

    private void jtfBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfBairroActionPerformed

    private void jtfCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCpfActionPerformed

    private void jtfNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNascimentoActionPerformed

    private void jtfVencimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfVencimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfVencimentoActionPerformed

    private void jtfUnidadeConsumidoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfUnidadeConsumidoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfUnidadeConsumidoraActionPerformed

    private void jtfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEmailActionPerformed

    private void jtfKwhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfKwhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfKwhActionPerformed

    private void cbSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSexoActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:

        String nome = jtfNome.getText();
        String sexo = (String) cbSexo.getSelectedItem();
        String endereco = jtfEndereco.getText();
        int cep =Integer.parseInt(jtfCep.getText());
        String bairro = jtfBairro.getText();
        int cpf =Integer.parseInt( jtfCpf.getText());
        String nascimento = jtfNascimento.getText();
        String vencimento = jtfVencimento.getText();
        String unidade = jtfUnidadeConsumidora.getText();
        String email = jtfEmail.getText();
        int kwh = Integer.parseInt(jtfKwh.getText());
        int valortotal = Integer.parseInt(jtfValorTotal.getText());
        String site = jtfSite.getText();
        
        Cliente cliente = new Cliente(nome, sexo, endereco, cep, bairro, cpf, nascimento, vencimento, unidade, email, kwh, valortotal, site);
        try {
            clientedao.adicionar(cliente);
            JOptionPane.showMessageDialog(null, "Pessoa Cadastrada");
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro na hora de inserir os dados", "Erro", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnGerarNota2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarNota2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGerarNota2ActionPerformed

    private void jtfSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSiteActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnGerarNota2;
    private javax.swing.JComboBox<String> cbSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jtfBairro;
    private javax.swing.JTextField jtfCep;
    private javax.swing.JTextField jtfCpf;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfEndereco;
    private javax.swing.JTextField jtfKwh;
    private javax.swing.JTextField jtfNascimento;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfSite;
    private javax.swing.JTextField jtfUnidadeConsumidora;
    private javax.swing.JTextField jtfValorTotal;
    private javax.swing.JTextField jtfVencimento;
    // End of variables declaration//GEN-END:variables
}
